config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'

  post 'api/v1/playlists', to: 'api/v1/playlists#create'
  get '/auth/fitbit_oauth2/callback', to: 'sessions#create'
  get '/auth/spotify/callback', to: 'sessions#complete'
  get '/spotify_login', to: 'pages#spotify_login', as: :spotify_login
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  get '/logout', to: 'sessions#destroy', as: :logout
  get 'api/v1/playlists/:id', to: 'api/v1/playlists#show', as: :playlist


end

app/models/fitbit_credential.rb
class FitbitCredential < ActiveRecord::Base
  belongs_to :user
end

app/models/fitbit_day.rb
class FitbitDay
  attr_reader :date, :rest, :low, :med, :high, :rest_rate
  
  def initialize(day)
    @date = Date.parse(day['dateTime'])
    @rest = day['value']['heartRateZones'].first['caloriesOut'].to_i
    @low = day['value']['heartRateZones'][1]['caloriesOut'].to_i
    @med = day['value']['heartRateZones'][2]['caloriesOut'].to_i
    @high = day['value']['heartRateZones'].last['caloriesOut'].to_i
    @rest_rate = day['value']['restingHeartRate']
  end

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user

   def tracks
    PlaylistManager.retrieve_playlist(user, spotify_id)
  end

end

app/models/spotify_credential.rb
class SpotifyCredential < ActiveRecord::Base
  belongs_to :user
end

app/models/track.rb
class Track
attr_reader :name, :artist, :album, :spotify_id

def initialize(name, artist, album, spotify_id)
  @name = name
  @artist = artist
  @album = album
  @spotify_id = spotify_id
end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :spotify_credential
  has_one :fitbit_credential
  has_many :playlists

  def self.login_with_fitbit(auth)
    user = find_or_create_by( name: auth[:info][:name] )
    user.create_or_update_fitbit_credential(auth)
    return user  
  end

  def add_data_from_spotify(auth)
    add_email_to_attributes(auth)
    create_or_update_spotify_credential(auth)
  end

  def create_or_update_fitbit_credential(auth)
    FitbitCredential.find_or_initialize_by( uid: auth[:uid] ).update_attributes!(
                      token: auth[:credentials][:token],
                      refresh_token: auth[:credentials][:refresh_token],
                      expiration_date: Time.at(auth[:credentials][:expires_at].to_i),
                      user_id: id )
  end

  def create_or_update_spotify_credential(auth)
    SpotifyCredential.find_or_initialize_by( uid: auth[:uid] ).update_attributes!(
                      token: auth[:credentials][:token],
                      refresh_token: auth[:credentials][:refresh_token],
                      expiration_date: Time.at(auth[:credentials][:expires_at].to_i),
                      user_id: id )
  end

  def add_email_to_attributes(auth)
    update!( email: auth[:info][:email] )
  end

  def verify_spotify_token
    response = refresh_spotify_token if spotify_credential.expiration_date < DateTime.now
    update_spotify_credentials(response) if response
    return self
  end

  def verify_fitbit_token
    response = refresh_fitbit_token if fitbit_credential.expiration_date < DateTime.now
    update_fitbit_credentials(response) if response
    return self
  end

  def fitbit_data
    raw_data = FitbitService.get_heart_data(fitbit_credential.uid, fitbit_credential.token)
    
    parsed_data = HeartDataParser.new(raw_data)
    response = parsed_data.day_array.last if parsed_data.day_array
  end

  def refresh_spotify_token
    response = SpotifyService.get_refresh_token(spotify_credential.refresh_token)
  end

  def refresh_fitbit_token
    response = FitbitService.get_refresh_token(fitbit_credential.refresh_token)
  end

  def update_spotify_credentials(response)
    spotify_credential.update!(token: response["access_token"], expiration_date: (DateTime.now + 1.hour))
    spotify_credential.update!(refresh_token: response["refresh_token"]) if response['refresh_token']
  end

  def update_fitbit_credentials(response)
    fitbit_credential.update!(token: response["access_token"], expiration_date: (DateTime.now + 1.hour))
    fitbit_credential.update!(refresh_token: response["refresh_token"]) if response['refresh_token']
  end

end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery with: :null_session
  respond_to :json

end

app/controllers/api/v1/playlists_controller.rb
class Api::V1::PlaylistsController < Api::V1::BaseController

def create
  session[:user_id] = params[:user]
  playlist = PlaylistManager.create_playlist(current_user, params[:intensity], params[:name])
  # result = PlaylistManager.populate_playlist(playlist.spotify_id, playlist.genre, playlist.intensity, playlist.user)
  # binding.pry
end

def show
  @playlist = Playlist.find_by(id: params[:id])
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :refresh_tokens_as_necessary
  

  private

  def current_user
    @current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
  end

  def refresh_tokens_as_necessary
    current_user.verify_fitbit_token
    current_user.verify_spotify_token
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
include WelcomeHelper

def welcome
  redirect_to dashboard_path if user_logged_in
  return_page_content(current_user, session[:spotify], session[:fitbit])
end

def dashboard
  redirect_to root_url if !current_user
  refresh_tokens_as_necessary
  @heart_day = current_user.fitbit_data
end

private

def user_logged_in
  current_session_has_login_info
end

def current_user_has_credentials
  (current_user != nil ) && (current_user.fitbit_credential != nil) && (current_user.spotify_credential != nil)
end

def current_session_has_login_info
  ( current_user ) && ( session[:fitbit] ) && ( session[:spotify] )
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    current_user = User.login_with_fitbit(request.env['omniauth.auth'])
    session[:user_id] = current_user.id
    session[:fitbit] = true
    redirect_to root_url
  end

  def complete
    current_user.add_data_from_spotify(request.env['omniauth.auth'])
    session[:user_id] = current_user.id
    session[:spotify] = true
    redirect_to dashboard_path, success: "Welcome to Fitbeat, #{current_user.name}"
  end

  def destroy
    session.clear
    redirect_to root_url, notice: "Successfully Signed Out"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

def return_page_content(user, spotify_logged_in, fitbit_logged_in)
  fitbit_content if !fitbit_logged_in
  spotify_content(user) if fitbit_logged_in
end

def spotify_content(user=nil)
    name = ", #{user.name}" if user
    @title = "Hey#{name}"
    @link_text = "Please sign into "
    @link_image = "spotify-sym.png"
    @path = "/auth/spotify"
    @name = " Spotify"
    @link_size = "30"
end

def fitbit_content
    @title = "Welcome to Fitbeat"
    @link_text = "Sign in with "
    @link_image = "fitbit-sym.png"
    @path = "/auth/fitbit_oauth2"
    @name = " Fitbit"
    @link_size = "70"
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>fitBEAT</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://fonts.googleapis.com/css?family=ABeeZee|Open+Sans|Ubuntu" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>
  <body>

      <%= yield %>


    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  </body>
</html>

app/views/pages/_chart.html.erb
 <% if @heart_day %>
 <div class="chart-box duck">
	<script>
window.onload = function () {
	var chart = new CanvasJS.Chart("chartContainer", {
		theme: "theme1",//theme1
		title:{
			text: "Calories Burned by Intensity",
			fontFamily: 'Ubuntu',
			fontSize: 24,
			// fontColor: "#4d4d4d",
			fontWeight: 400,
			verticalAlign: "top"
		},
		animationEnabled: true,   // change to true
		data: [              
		{
			// Change type to "bar", "area", "spline", "pie",etc.
			type: "pie",
			indexLabelFontColor: "#4d4d4d", 
			indexLabelLineColor: "#4d4d4d",        
			indexLabelFontWeight: "bold",        
			indexLabelLineThickness: 1.25,        
			indexLabelPlacement: "outside",
			toolTipContent: "{y} cal",

			dataPoints: [
			<% if @heart_day.high != 0 %>
				{ label: "peak",  y: <%= @heart_day.high %>  },
			<% end %>
			<% if @heart_day.med != 0 %>
				{ label: "medium", y: <%= @heart_day.med %>, color: "#004080"  },
			<% end %>
			<% if @heart_day.low != 0 %>
				{ label: "low", y: <%= @heart_day.low %>, exploded: true, color: "#408000" },
			<% end %>
			<% if @heart_day.rest != 0 %>
				{ label: "at rest",  y: <%= @heart_day.rest %>, color: "#800080"  }
			<% end %>
			]
		}
		]
	});
	chart.render();
}
</script>
</head>
<body>
<div id="chartContainer" style="height: 285px; width: 100%; padding: 0px; margin: 0px;" class="chart-round"></div>
</script>
</div>
<% end %>

app/views/pages/_create_playlist.html.erb
<div class="create-playlist-box m-bott">
<div class="form-box">
	<h4 class="create-heading">Create a New Playlist:</h4>
		<div class="input-group form-inline">

      <%= text_field_tag :play_name, nil, placeholder: "Playlist Title", class:"form-control txt m-bott" %>

      <%= select_tag "play_intensity", options_for_select(['Intensity:', 'High', 'Med', 'Low', 'Rest', 'None'], 'Intensity:'), class: 'btn btn-primary-outline space' %>

      <%= select_tag "play_genre", options_for_select(['Genre:', 'Ambient', 'Bluegrass', 'Classical', 'Club/Dance', 'Dub', 'Electronic', 'Folk', 'Funk', 'Hip-Hop', 'House', 'Jazz', 'Old-Timey', 'Pop', 'Indie Pop', 'Punk', 'Rap', 'Reggae', 'Rock', 'Indie Rock', 'Salsa', 'Soul', 'Techno'], 'Genre:'), class: 'btn btn-primary-outline' %>

      <%= hidden_field_tag 'user_id', current_user.id %>

      <button id="create_playlist" class="btn btn-primary-outline btn-sm btn-create">Create</button>

    </div>
</div>

</div>
</div>

app/views/pages/_heart_menu.html.erb
<% if @heart_day %>
<div class="list-group">
	<a href="#" class="list-group-item" id="heart-title">
		<h4 class="list-group-item-heading" id="activity-title">My Heart Rate Activity:</h4>
		<small class="text-muted hide" id="heart-date">last updated 
			<%=l @heart_day.date, format: :long %></small> 
	</a>
	<a href="#" class="list-group-item heart-data" id="peak-box">
		<h5 class="list-group-item-heading">Peak Intensity</h5>
		<p class="list-group-item-text heart-hide hide" id="peak-data">
			<%= @heart_day.high %> calories burned at a heart rate between 161 and 220 bpm
		</p>
	</a>
	<a href="#" class="list-group-item heart-data" id="med-box">
		<h5 class="list-group-item-heading">Medium Intensity</h5>
		<p class="list-group-item-text heart-hide hide" id="med-data">
			<%= @heart_day.med %> calories burned at a heart rate between 131 and 160 bpm
		</p>
	</a>
	<a href="#" class="list-group-item heart-data" id="low-box">
		<h5 class="list-group-item-heading">Low Intensity</h5>
		<p class="list-group-item-text heart-hide hide" id="low-data">
			<%= @heart_day.low %> calories burned at a heart rate between 96 and 130 bpm
		</p>
	</a>
	<a href="#" class="list-group-item heart-data" id="rest-box">
		<h5 class="list-group-item-heading">At Rest</h5>
		<p class="list-group-item-text heart-hide hide" id="rest-data">
			<%= @heart_day.rest %> calories burned at a heart rate below 95 bpm
		</p>
	</a>
</div>
<% else %>
	<div class='card empty'>No Heart Data :(</div>
<% end %>

app/views/pages/_heart_rate.html.erb
 <% if @heart_day %>
 <div id="heart-card" class="card form-box2">

	<div class="col-md-6 col-sm-12 col-xs-12">
		Resting Heart Rate
	</div> 
	<div class="col-md-6 col-sm-12 col-xs-12">
		<div class="rate-rate"><%= @heart_day.rest_rate %></div>
		bpm ♥
	</div>

</div>
<% end %>

app/views/pages/_navbar.html.erb
<div class="navbar">
	<span class="nav-header">fit</span>
	<span class="nav2">BEAT</span>
	<span class="btn btn-sm r-align btn-warning-outline btn-logout">
		<%= link_to 'logout', '/logout' %>
	</span>
</div>

app/views/pages/_playlist_index.html.erb
<div class="list-group playlist-box">
	<a href="#" class="list-group-item">
		<h3 class="list-group-item-heading">My Fitbeat Playlists:</h3>
	</a>
	<% if current_user.playlists.empty? %>
		<h5><a href="#" class="list-group-item">No playlists yet. Create one above!</a></h5>
	<% else %>
		<% current_user.playlists.each do |playlist| %>
	
			<%= link_to playlist.name[0..-11], playlist_path(playlist), class: "list-group-item font-up list-group-item" %>
			
		<% end %>
	
	<% end %>
</div>

app/views/pages/dashboard.html.erb
<div class="backstretch" id="backstretch2">
	<div class="container dash-box">
		<%= render 'navbar' %> 

		<div class="dash-inner">

			<div class="col-md-4 heart-box">
				<%= render 'heart_menu' %>
				<%= render 'chart' %>
			</div>

			<div class="col-md-3">
				<%= render 'heart_rate' %>
			</div>

			<div class="col-md-5">
				<%= render 'create_playlist' %>
			</div>

			<div class="col-md-8">
				<%= render 'playlist_index' %>
			</div>

		</div>

	</div>
</div>

app/views/pages/spotify_login.html.erb
<%= link_to "Log in with Spotify", "/auth/spotify" %>

app/views/pages/welcome.html.erb
<div id="backstretch1" class="backstretch">
  
  <div class="login-box"></div>
  <div class="login-blur"></div>
	<div class="login-solid">
  <div class="login animated fadeIn">
  		<span class="welcome-title"><%= @title %></span>
      <%= button_to "#{@path}",  class: "btn btn-lg btn-login-outline login-btn-text" do %><%= @link_text %><%= image_tag( @link_image, width: 20, class: 'bump') %><%= @name %><% end %>
  </div>
</div>
 

</div>